[package]
name = "randme"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }

[addresses]
sui =  "0000000000000000000000000000000000000002"
randme = "0x6e37bcfe8f8e11ba7f6b8a66d5d0b65208a42a4c"